### ISSUE TITLE
Can't publish a React Native Project on Android. Expo Deprecated

### ISSUE THREAD

**Issue by robkinobi** [robkinobi/Nativity#3]
I'm having a real headache trying to get my Expo React Native app published on Android. Every time I try, it just fails. And now, the Expo ID I used to rely on is no longer an option. What's the deal? How can I get this sorted out and finally publish my app on Android?

**Comment by izustic** [comment]
Expo is deprecated. Eas is what is used now. To publish your react native app as a .apk file, you need to first create an eas.json file. For example,
```
{
  "cli": {
    "version": ">= 0.52.0"
  },
  "build": {
    "development": {
      "developmentClient": true,
      "distribution": "internal"
    },
    "preview": {
      "distribution": "internal"
    },
    "production": {
      "android": {
        "buildType": "apk"
      }
    }
  },
  "submit": {
    "production": {}
  }
}
```
Then you run the following command
```
eas build -p android --profile preview
```
regards.
